@startuml
(*)  --> "ユーザーターン" as userturn
--> "ユーザータッチイベント"
--> "サイコロ結果算出" as DIS
--> "ユーザー駒　＋=サイコロ値"
--> "ユーザー駒　マップ上を取得サイコロ値分移動"
If "ユーザー駒マス値　=　ゴールマス値" then
--> [Yes]"占い結果画面に遷移"
--> (*)
else
-->"COM駒挙動処理"
-->"サイコロ結果算出"
-->"COM駒マス値 +=サイコ
--> "COM駒　マップ上を取得サイコロ値分移動"
If "COM駒マス値　=　ゴールマス値" then
--> [Yes] "COM駒順位設定"
else
--> ["COM駒マス値 > ゴール値 "] "COM駒　=　ゴールマス値 -(COM駒マス-ゴールマス値)"
--> "COM駒をゴールマスから(COM駒マス-ゴールマス値)分　スタート方向に移動"
Endif
Endif
--> userturn
@enduml